steps:
  - input: ":white_check_mark: Get Definition"
    key: "definitionPath"
    fields:
      - select: "Branch Release Stream"
        key: "branch-release-stream"
        hint: "Which release stream does this belong in? :fork:"
        options:
          - label: "MST01"
            value: "release-docs-mst01"
      - text: "Release Version #"
        key: "release-version"
        hint: "What's the # name for this release? :name_badge:"

  - label: Test
    commands: .buildkite/script.sh mst01
